<?php

namespace MainBundle\Repository;

/**
 * Application Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Application Repository extends \Doctrine\ORM\EntityRepository
{
}
